cities=["New York,US","Los Angeles,US","Chicago,US","Houston,US",
"Phoenix,US","London,GB","Manchester,GB",
"Birmingham,GB","Glasgow,GB","Liverpool,GB",
"Toronto,CA","Vancouver,CA","Montreal,CA",
"Calgary,CA","Ottawa,CA","Paris,FR","Lyon,FR",
"Marseille,FR","Nice,FR","Toulouse,FR",
"Berlin,DE","Munich,DE","Hamburg,DE",
"Frankfurt,DE","Cologne,DE","Tokyo,JP",
"Osaka,JP","Kyoto,JP","Nagoya,JP","Fukuoka,JP",
"Sydney,AU","Melbourne,AU","Brisbane,AU","Perth,AU",
"Adelaide,AU","Delhi,IN","Mumbai,IN",
"Bengaluru,IN","Chennai,IN","Hyderabad,IN",
"Dubai,AE","Abu Dhabi,AE","Doha,QA","Riyadh,SA","Jeddah,SA",
"Cape Town,ZA","Johannsburg,ZA","Cairo,EG","Nairobi,KE","Lagos,NG"]